name: Testing

on:
  push:
    branches:
      - main
    paths-ignore:
      - '**.md'
      - '.eslintrc.js'
      - '.prettierrc'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 16.x
        uses: actions/setup-node@v2
        with:
          node-version: 16.x
      - uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}
      - name: build and test
        run: |
          yarn
          yarn test
          yarn build
